### PR TITLE
Refactor: improve testability by extracting pure code from M.comment_*

### PR DESCRIPTION
**Pull request by YodaEmbedding**
## Improving testability

This pull request makes the commenting logic testable.

In `kommentary.lua`, all the `M.comment_in/out_*` functions have been split into two functions: one impure and one pure. For instance, the code contained in `M.comment_in_range_single` is now broken into the following two:

```lua
function M.comment_in_range_single          -- impure (has I/O effects)
function M.comment_in_range_single_content  -- pure   (no side effects)
```

The impure function calls `vim.api.nvim_buf_get_lines`, `vim.api.nvim_buf_set_lines`, and the pure function. This separation makes it much easier to write tests for the pure `M.comment_*_content` functions. For small functions such as `M.comment_in_line`, this splitting may seem trivial (converting a 4 line function into two 2 line functions), but I did these small functions as well in order to maintain consistency. The changes are kept minimal where possible (restricted to copy/paste extracting the code) to make it easier for you to verify the diffs. Since it is only refactoring, there are (hopefully) no functional changes made in this commit.

---

## Tests

I have not created these yet, but I am imagining something like:

```lua
comment_in_range_tests = {
    {
        language = "python",
        line_number_start = 2,
        line_number_end = 5,
        content = [[
            class Functor:
                def __init__(self):
                    ...

                    pass
        ]],
        expected = [[
            class Functor:
                # def __init__(self):
                #     ...
                #
                #     pass
        ]],
    },

    -- ... more test cases ...
}
```

These tests will be applied to the `M.comment_in_range_content` functions directly in order to check the resulting strings.

### CODE REVIEW

**Comment by b3nj5m1n** [comment]
Thank you so much, this is awesome. I've been meaning to do such a refactor for a while now, but unfortunately I haven't had much time lately.

There's really only one "*problem*", none of the `*_content` functions are documented, and the documentation for the other functions is a little off now. I'll try to just change that myself, then we can merge.

One question, are you going to write some tests yourself? As I said, I currently don't have too much time, and coming up with all the relevant test cases is going to be quite time-consuming. If you don't want to that's completely fine of course, it'll just take some time till I get around to doing it.

**Review by b3nj5m1n — APPROVED** [review]
Thanks a lot for this again!

**Comment by YodaEmbedding** [comment]
> One question, are you going to write some tests yourself?

I was planning on doing so, although I might not get around to completing them for a while.

I tried running the test suite but since the code contains references to `vim.*`,  it errors out:

```
$ ./run_tests.sh

Running Config Tests
===============================================================
Started on Sun Feb 28 03:48:34 2021
    Test_Config.test_config_from_commentstring ... ERROR
./kommentary/config.lua:252: attempt to index a nil value (global 'vim')
    Test_Config.test_get_config ... ERROR
```

How is your test environment set up?

**Comment by b3nj5m1n** [comment]
That's the same I get, since the tests weren't very useful previously, I haven't been updating them for a while. Atm you can pretty much ignore the tests, that's why I was really happy to see this PR.

**Pull request merged**
